const source=require('node:fs').readFileSync('check-flows.cjs','utf8');
new Function('require',source+`
vm.runInContext(fs.readFileSync('dist/workflow.js','utf8'),sandbox);
for(const s of ['.receipt','#party-form','#overlay','#purchase-form'])node(s).insertAdjacentHTML=function(where,html){this.innerHTML+=html};
run("db=seed();db.cheques=[];purchaseLines=[];purchaseForm()");
assert.ok(node('#overlay').innerHTML.includes('Added stock'));
assert.ok(node('#overlay').innerHTML.includes('Product name (optional)'));
assert.ok(!node('#overlay').innerHTML.includes('Colour'));
assert.ok(run("tenderFields('purchase').includes('purchase-number')"));
assert.ok(run("tenderFields('purchase').includes('purchase-bankName')"));
sandbox.FormData=function(){return Object.entries(sandbox.form||{})};
sandbox.form={supplier:'s1',date:'2026-09-22',batch:'RCH-B09',name:'',article:'',size:'Unstitched',qty:'10',cost:'1200',price:'1800',location:'Rack C1',paid:'0'};
node('#purchase-cash').value='0';node('#purchase-bank').value='0';node('#purchase-cheque').value='5000';node('#purchase-number').value='SUP-001';node('#purchase-bankName').value='Meezan Bank';node('#purchase-date').value='2026-09-22';
run("purchaseLines=[{supplier:'s1',date:'2026-09-22',batch:'RCH-B09',name:'',article:'',size:'Unstitched',qty:10,cost:1200,price:1800,location:'Rack C1'}];savePurchase()");
eq('db.products.at(-1).color','');eq('db.products.at(-1).article','');eq("db.products.at(-1).name",'Unnamed item · RCH-B09');eq('db.products.at(-1).stock',10);eq('db.purchases[0].total',12000);eq('db.cheques[0].number','SUP-001');eq('db.cheques[0].party','s1');eq('db.cheques[0].amount',5000);eq("supplierBalance('s1')",80000);
node('#cheque-status').value='Cleared';node('#cheque-clear-date').value='2026-09-23';run('saveChequeOutcome(db.cheques[0].id)');eq("supplierBalance('s1')",75000);
run("db=seed();db.cheques=[];resetCart();customer='c1';saleReturnLines=[];saleReturnCode='RCH-B01-BLU'");node('#sale-return-qty').value='1';node('#sale-return-condition').value='sellable';run('addSaleReturnByCode()');eq('saleReturnLines[0].rate',undefined);eq('cart[0].price',-1944.44);
run("addItem('p3');dueDate='2026-10-01'");node('#sale-cash').value='655.56';run('saveSale()');eq('db.sales[0].total',655.56);eq('db.sales[0].returnsApplied.length',1);eq('db.sales[0].returnsApplied[0].price',1944.44);eq("product('p1').stock",109);eq("product('p3').stock",47);eq("availableReturnQty('p1','c1')",11);eq("returned('INV-1052','p1')",1);
console.log('PASS: multi-line receiving preview, optional product/article, no colour field, code-based return at original rate, net bill and stock update.');
`)(require);
